app:
  security:
    jwt:
      accessSecret: yourAccessSecret
      refreshSecret: yourRefreshSecret
      prefix: Bearer
      authHeader: Authorization
      accessExpiresAt: 3600000 # 1 hour in milliseconds
      refreshExpiresAt: 86400000 # 1 day in

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2251120374@ut.edu.vn
    password: khongcopass
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: 2251120374@ut.edu.vn

  kafka:
    bootstrap-servers: localhost:9092

endpoint:
  confirmUser: http://localhost:8081/api/v1/auth/confirm   # Địa chỉ xác thực người dùng